# Not the correct language, but one that has very few dependancies to install
language: c

before_script:
    - sudo apt-get update
    - sudo make build-deps

script:
    - make patch_enable_battery
    - make test
    - rm -f .config
    - make test
    - make test.img.orig

after_success:
    - make test.report
