---
# CI config for https://github.com

name: CI

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 0 1 * *'

jobs:
    check:
        name: make test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Fix Checkout
              run: |
                git fetch --force --tags

            - name: Prepare environment
              run: |
                touch .config
                sudo make build-deps

            - name: Test with both patches enabled
              run: |
                make patch_enable_keyboard patch_enable_battery
                make test

            - name: Test with batteryonly targets
              run: |
                make patch_disable_keyboard patch_enable_battery
                make test.batteryonly

            - name: Test with default build
              run: |
                rm -f .config
                make test

            - name: Test we can download all known Lenovo files
              run: |
                make test.img.orig

            - name: Make a test report
              run: |
                make test.report

            - name: Upload lenovo files
              uses: actions/upload-artifact@v2
              with:
                name: lenovo-files
                path: |
                  *.iso.orig
                  *.exe.orig
